server:
  port: 8087
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: http://localhost:8084
          predicates:
            - Path=/product/**
        - id: ORDER-SERVICE
          uri: http://localhost:8085
          predicates:
            - Path=/order/**
        - id: PAYMENT-SERVICE
          uri: http://localhost:8086
          predicates:
            - Path=/payment/**